// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViewModel.Data;

#nullable disable

namespace ViewModel.Migrations
{
    [DbContext(typeof(ViewModelContext))]
    partial class ViewModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ViewModel.Models.A", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("One")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Three")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Two")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("A");
                });

            modelBuilder.Entity("ViewModel.Models.B", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("One")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Three")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Two")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("B");
                });

            modelBuilder.Entity("ViewModel.Models.C", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AId")
                        .HasColumnType("int");

                    b.Property<int>("BId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AId");

                    b.HasIndex("BId");

                    b.ToTable("C");
                });

            modelBuilder.Entity("ViewModel.Models.C", b =>
                {
                    b.HasOne("ViewModel.Models.A", "A")
                        .WithMany("C")
                        .HasForeignKey("AId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViewModel.Models.B", "B")
                        .WithMany("C")
                        .HasForeignKey("BId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("A");

                    b.Navigation("B");
                });

            modelBuilder.Entity("ViewModel.Models.A", b =>
                {
                    b.Navigation("C");
                });

            modelBuilder.Entity("ViewModel.Models.B", b =>
                {
                    b.Navigation("C");
                });
#pragma warning restore 612, 618
        }
    }
}
